-- AlterTable
ALTER TABLE `Entry` MODIFY `chain` ENUM('BTC', 'BNB', 'ETH', 'MATIC', 'SOLANA', 'ARBITRUM', 'ARBITRUM_NOVA', 'ARBITRUM_ONE', 'OPTIMISM') NOT NULL;

-- AlterTable
ALTER TABLE `EntryComparison` MODIFY `chain` ENUM('BTC', 'BNB', 'ETH', 'MATIC', 'SOLANA', 'ARBITRUM', 'ARBITRUM_NOVA', 'ARBITRUM_ONE', 'OPTIMISM') NOT NULL;

-- AlterTable
ALTER TABLE `MoalisErc20Transaction` MODIFY `chain` ENUM('BTC', 'BNB', 'ETH', 'MATIC', 'SOLANA', 'ARBITRUM', 'ARBITRUM_NOVA', 'ARBITRUM_ONE', 'OPTIMISM') NOT NULL;

-- AlterTable
ALTER TABLE `ScannerInternalTransaction` MODIFY `chain` ENUM('BTC', 'BNB', 'ETH', 'MATIC', 'SOLANA', 'ARBITRUM', 'ARBITRUM_NOVA', 'ARBITRUM_ONE', 'OPTIMISM') NOT NULL;

-- AlterTable
ALTER TABLE `ScannerTransaction` MODIFY `chain` ENUM('BTC', 'BNB', 'ETH', 'MATIC', 'SOLANA', 'ARBITRUM', 'ARBITRUM_NOVA', 'ARBITRUM_ONE', 'OPTIMISM') NOT NULL;

-- AlterTable
ALTER TABLE `Wallet` MODIFY `chain` ENUM('BTC', 'BNB', 'ETH', 'MATIC', 'SOLANA', 'ARBITRUM', 'ARBITRUM_NOVA', 'ARBITRUM_ONE', 'OPTIMISM') NULL,
    MODIFY `walletAddress` VARCHAR(191) NULL,
    MODIFY `tokenAddress` VARCHAR(191) NULL;
